name: Workflow Commands

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number
      comment_body:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:
  restart:
    name: Restart Workflow
    if: contains(inputs.comment_body, '/restart')
    uses: ./.github/workflows/restart.yml
    with:
      issue_number: ${{ inputs.issue_number }}
      repository: ${{ inputs.repository }}
    secrets: inherit
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

  split-test-check:
    name: Split Test Check
    if: contains(inputs.comment_body, '/split-test check')
    uses: ./.github/workflows/split-test-check.yml
    with:
      issue_number: ${{ inputs.issue_number }}
      repository: ${{ inputs.repository }}
    secrets: inherit
    permissions:
      issues: write

  pull-request:
    name: Pull Request
    if: contains(inputs.comment_body, '/pr')
    uses: ./.github/workflows/pull-request.yml
    with:
      issue_number: ${{ inputs.issue_number }}
      repository: ${{ inputs.repository }}
    secrets: inherit
    permissions:
      contents: read
      issues: write
      pull-requests: write